apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade,post-install,post-upgrade'
    helm.sh/hook-delete-policy: 'before-hook-creation,hook-succeeded'
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: ingress-nginx-4.0.1
  name: ingress-nginx-admission
  namespace: ingress-nginx
