[hololens]
container = "ghcr.io/hologit/lenses/helm3:latest"

[hololens.input]
root = "prevention-point"
files = "**"

[hololens.output]
merge = "replace"

[hololens.helm]
namespace = "prevention-point"
release_name = "prevention-point"

chart_path = "helm-chart"
value_files = [
    "release-values.yaml"
]
