apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: prometheus
    chart: prometheus-15.18.0
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
rules: []
