apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: balancer

resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml

images:
  - name: ghcr.io/codeforphilly/balancer-main/app
    newTag: "1.1.2"

patches:
  - target:
      kind: Ingress
      name: balancer
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: replace
        path: /spec/tls/0/hosts/0
        value: balancer.sandbox.k8s.phl.io
      - op: replace
        path: /spec/rules/0/host
        value: balancer.sandbox.k8s.phl.io
  - target:
      kind: Namespace
      name: balancer
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev
