apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: prometheus
    chart: prometheus-15.6.0
    component: node-exporter
    heritage: Helm
    release: prometheus
  name: prometheus-node-exporter
  namespace: prometheus
