apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    chart: prometheus-15.6.0
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: prometheus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
